#ifndef PINDEFS_H
#define PINDEFS_H

// Hardware Bridge Pins
#define ADDRESS_SERIAL_LATCH_PIN 3
#define ADDRESS_SERIAL_CLOCK_PIN 4
#define ADDRESS_SERIAL_DATA_PIN 5

#define STAGED_DATA_SERIAL_LATCH_PIN 6
#define STAGED_DATA_SERIAL_CLOCK_PIN 7
#define STAGED_DATA_SERIAL_DATA_PIN 8

#define READ_DATA_SERIAL_LATCH_PIN 10
#define READ_DATA_SERIAL_CLOCK_PIN 11
#define READ_DATA_SERIAL_DATA_PIN 12

#define RAM_REGION_PIN 14
#define RAM_CONTROL_MODE_PIN 15
#define RESET_PIN 16
#define RAM_WRITE_SIGNAL_PIN 17
#define CLOCK_SOURCE_PIN 18
#define CLOCK_ENABLED_PIN 19
#define CLOCK_PIN 9

// LCD Pins
// N/A SCA is pin 20 and SCL pin 21 on a Mega (A4 and A5 on a Nano/Uno)

// Monitor Pins
#define DATA_KEYPAD_PIN A0
#define MINUS_BUTTON_PIN 22
#define CONTROL_KEYPAD_PIN A1
#define SPEED_POT_PIN A2

#endif