#ifndef PINDEFS_H
#define PINDEFS_H

// Hardware Bridge Pins
#define ADDRESS_SERIAL_LATCH_PIN 1
#define ADDRESS_SERIAL_CLOCK_PIN 2
#define ADDRESS_SERIAL_DATA_PIN 3

#define STAGED_DATA_SERIAL_LATCH_PIN 4
#define STAGED_DATA_SERIAL_CLOCK_PIN 5
#define STAGED_DATA_SERIAL_DATA_PIN 6

#define READ_DATA_SERIAL_LATCH_PIN 7
#define READ_DATA_SERIAL_CLOCK_PIN 8
#define READ_DATA_SERIAL_DATA_PIN 10

#define RAM_REGION_PIN 11
#define RAM_CONTROL_MODE_PIN 12
#define RESET_PIN 13
#define RAM_WRITE_SIGNAL_PIN -1
#define CLOCK_SOURCE_PIN 14
#define CLOCK_ENABLED_PIN 15
#define CLOCK_PIN 9

// LCD Pins

// Monitor Pins

#endif